spring:
  application:
    name: "scatter-controller"
  zipkin:
    sender: web
    base-url: "http://127.0.0.1:9411/"
    service:
      name: "scatter-controller"
  sleuth:
    sampler:
      probability: 1.0
logging:
  pattern:
    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"